const slideDiv = document.querySelector('.slideDiv')
const button = document.querySelector('.menuHolder')
const services = document.querySelector('#services')
const portfolio = document.querySelector('#portfolio')
const about = document.querySelector('#about')
const team = document.querySelector('#team')
const contact = document.querySelector('#contact')
const topLine = document.querySelector('.top')
const bottomLine = document.querySelector('.bottom')
const middleLine = document.querySelector('.middle')
console.log(button)
console.log(slideDiv)
button.addEventListener('click', changeSlide)

function changeSlide () {
    console.log(slideDiv.id)
    switch (slideDiv.classList[1]) {
        case 'hidden': 
            slideDiv.classList.remove('hidden')
            slideDiv.classList.add('active')
            services.classList.remove('itemOneHide')
            services.classList.add('itemOne')
            portfolio.classList.remove('itemTwoHide')
            portfolio.classList.add('itemTwo')
            about.classList.remove('itemThreeHide')
            about.classList.add('itemThree')
            team.classList.remove('itemFourHide')
            team.classList.add('itemFour')
            contact.classList.remove('itemFiveHide')
            contact.classList.add('itemFive')
            bottomLine.classList.remove('bottomHide')
            bottomLine.classList.add('bottomActive')
            topLine.classList.remove('topHide')
            topLine.classList.add('topActive')
            middleLine.classList.remove('middleHide')
            middleLine.classList.add('middleActive')

            console.log('Working')
            break
        case 'active':
            slideDiv.classList.remove('active')
            slideDiv.classList.add('hidden')
            services.classList.remove('itemOne')
            services.classList.add('itemOneHide')
            portfolio.classList.remove('itemTwo')
            portfolio.classList.add('itemTwoHide')
            about.classList.remove('itemThree')
            about.classList.add('itemThreeHide')
            team.classList.remove('itemFour')
            team.classList.add('itemFourHide')
            contact.classList.remove('itemFive')
            contact.classList.add('itemFiveHide')
            bottomLine.classList.remove('bottomActive')
            bottomLine.classList.add('bottomHide')
            topLine.classList.remove('topActive')
            topLine.classList.add('topHide')
            middleLine.classList.remove('middleActive')
            middleLine.classList.add('middleHide')
            break
        default:
            slideDiv.classList.add('active')
            services.classList.add('itemOne')
            portfolio.classList.add('itemTwo')
            about.classList.add('itemThree')
            team.classList.add('itemFour')
            contact.classList.add('itemFive')
            bottomLine.classList.add('bottomActive')
            topLine.classList.add('topActive')
            middleLine.classList.add('middleActive')
    }
    console.log('working')
}